yaml
name: Run News Bot

on:
  schedule:
    - cron: '0 */3 * * *' # هر 3 ساعت یکبار اجرا می‌شود
  workflow_dispatch: # اجازه می‌دهد دستی هم اجرا کنید

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Bot
      
      run: python your_bot_file_name.py
